spring.application.name=petadoption
spring.datasource.url=jdbc:mysql://localhost:3306/petadoption
spring.datasource.username=root
spring.datasource.password=Ramya@sri29

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver